---
# tasks file for logrotate

- name: Install logrotate
  package:
    name: logrotate
    state: present

- name: Setup logrotate.d scripts
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
  with_items: "{{ logrotate_scripts }}"
