---
# tasks/main.yml (logrotate)
# Prefix : logrotate

- name: Install tasks
  import_tasks: install.yml
  when:
    - logrotate_install_flag | bool
  tags: ["install"]

- name: Configure tasks
  import_tasks: configure.yml
  tags: ["configure"]
